---
# tasks file for kfiresmith.logwatch

  - name: install logwatch package
    ansible.builtin.package:
      name: logwatch

  - name: install logwatch.conf template
    ansible.builtin.template:
      src: logwatch.conf.j2
      dest: /etc/logwatch/conf/logwatch.conf
      owner: root
      group: root
      mode: '0644'

  - name: install logwatch ignore.conf template
    ansible.builtin.template:
      src: logwatch-ignore.conf.j2
      dest: /etc/logwatch/conf/ignore.conf
      owner: root
      group: root
      mode: '0644'
